sudo: false

language: cpp

matrix:
  include :
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev']
      install: export CXX="g++-4.9" CC="gcc-4.9"

before_script:
 #- git clone https://github.com/seqan/seqan.git seqan
 - wget https://github.com/seqan/seqan/archive/seqan-v2.2.0.tar.gz
 - tar xvf seqan-v2.2.0.tar.gz
 - mv seqan-seqan-v2.2.0 seqan
 - git clone git@github.com:martinjvickers/methylation_tools.git

script:
 # compile run and app test unique_read_extractor
 - cd methylation_tools/unique_read_extractor
 - cmake ../unique_read_extractor -DCMAKE_MODULE_PATH=../../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make -j2
 - ./unique_read_extractor -i example_data/subsample.sam -o example_data/new_result.sam
 - diff example_data/result.sam example_data/new_result.sam
 # compile run and app test w50_creator
 - cd ../w50_creator
 - cmake ../w50_creator -DCMAKE_MODULE_PATH=../../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make -j2
 - ./w50_creator -i example_data/GSM952438_TFH39.all.cg-col.gff.gz -s 50 -l window -p dzlab > result.w50.gff
 - diff result.w50.gff example_data/GSM952438_TFH39.all.cg-col.DZ.w50_mod.gff
